version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - c://mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGOEXPRESS_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123